# Site settings
title:              Jen Does Things
description:        Elegant Solutions, Rewarding Experiences
baseurl:            ''
url:                https://www.jendoesthings.com
siteurl:            https://www.jendoesthings.com
email:              germanny@gmail.com
markdown:           kramdown
collections_dir:    _collections
includes_dir:       _html/_includes
layouts_dir:        _html/_layouts
image_base:         /assets/images/


collections:
  pages:
    output:          true
    permalink:       :path
  shy-dogs:
    output:          true


# Defaults
defaults:
  - scope:
      path:          ""
    values:
      layout:        "default"

# Exclude Output Directory
exclude:            [README.md, Gemfile, Gemfile.lock]

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-cloudinary

cloudinary:
  cloud_name:       germanny
  verbose:          true
  presets:
    default:
      min_width:            340
      max_width:            730
      fallback_max_width:   730
      steps:                3
      sizes:                "(min-width: 50rem) 50rem, 90vw"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
